apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sec-dgr
spec:
  replicas: {{ .Values.environment.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1          # 同時最多多啟動 1 個新 Pod（預設 25%）
      maxUnavailable: 1    # 同時最多中斷 1 個舊 Pod（預設 25%）
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sec-dgr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sec-dgr
    spec:
      initContainers:
        - name: init-environment
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Hello world"
             
              while ! nc -z main-dgr-service {{ .Values.environment.dgr.service.port}} ; do
                echo "waiting for main dgr service"
                sleep 2
              done
              echo "main dgr service is up"
      containers:
        - name: {{ .Release.Name }}-sec-dgr
          ports:
          - containerPort: {{ .Values.environment.dgr.container.port }}
          image: {{ .Values.environment.dgr.image.repo }}:{{ .Values.environment.dgr.image.tag }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              
              # 執行 Java，注意每個 -D 參數都要正確
              # 啟用容器支援與 JVM 相關參數
              exec java -cp app-cp/* \
                -XX:+UseContainerSupport \
                -XX:MaxDirectMemorySize=128m \
                -XX:MaxMetaspaceSize=256m \
                -Xss512k \
                -Xms2048m \
                -Dserver.undertow.direct-buffers=true \
                -Dloader.path=lib/,libsext/ \
                -Djava.security.debug=properties \
                -Djava.security.properties=./config/dgr.java.security \
                -Dspring.config.location=file:./config/ \
                -DdigiRunner.token.key-store.path=./keys \
                -Djasypt.encryptor.privateKeyLocation=file:./keys/enc.pem \
                -Dfile.encoding=UTF-8 \
                -Dlogging.config=file:./config/logback.xml \
                -Dspring.profiles.active=local \
                -Dserver.port={{ .Values.environment.dgr.container.port }} \
                -Ddigi.instance.id=gateway \
                -Dspring.sql.init.mode=$spring_sql_init_mode \
                -Des.apilog.allow.write.elastic=false \
                -Dserver.ssl.enabled=false \
                -Dspring.datasource.url='jdbc:h2:tcp://main-dgr-service:{{ .Values.environment.database.container.port }}/./db/dgrdb;NON_KEYWORDS=VALUE;Mode=MySQL' \
                org.springframework.boot.loader.launch.PropertiesLauncher
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 4048Mi
          livenessProbe:
            httpGet:
              path: /liveness  
              port: {{ .Values.environment.dgr.container.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /readiness 
              port: {{ .Values.environment.dgr.container.port }}      
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  # 檢查 HTTP endpoint 是否正常
                  if ! curl -sf http://127.0.0.1:{{ .Values.environment.dgr.container.port }}/liveness; then
                    echo "HTTP 檢查失敗"
                    exit 1
                  fi

            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 10
        - name: {{ .Release.Name }}-sec-composer
          image: {{ .Values.environment.composer.image.repo }}:{{ .Values.environment.composer.image.tag }}
          args:
            - "--node-options=--max-old-space-size=800"  
          env:
            - name: TZ
              value: Asia/Taipei
            - name: DIGIRUNNER_SCHEMES_MAIN
              value: http
            - name: DIGIRUNNER_HOST_MAIN
              value: 127.0.0.1
            - name: DIGIRUNNER_PORT_MAIN
              value: "{{ .Values.environment.dgr.container.port }}"
            - name: HTTPS_ENABLED_MAIN
              value: "false"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /editor/version 
              port: {{ .Values.environment.composer.container.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /editor/version 
              port: {{ .Values.environment.composer.container.port }}
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          startupProbe:
            httpGet:
              path: /editor/version  
              port: {{ .Values.environment.composer.container.port }}
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 10
