# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: {{ .Release.Name }}-sec-dgr-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: {{ .Release.Name }}-sec-dgr
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: AverageValue
#         averageValue: 3600Mi
#   behavior:
#     scaleUp:
#       stabilizationWindowSeconds: 0
#       policies:
#       - type: Percent
#         value: 100
#         periodSeconds: 60
#       selectPolicy: Max
#     scaleDown:
#       stabilizationWindowSeconds: 300
#       policies:
#       - type: Percent
#         value: 50
#         periodSeconds: 60
#       selectPolicy: Min
