apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.environment.persistentVolumeClaim.size }}
  storageClassName: {{ .Values.environment.persistentVolumeClaim.storageClass }}
